import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    // 배경색을 흰색으로 맞추기 위해 Light Theme를 사용합니다.
    return MaterialApp(
      theme: ThemeData.light().copyWith(
        scaffoldBackgroundColor: Colors.white,
      ),
      home: const Scaffold(
        // 화면이 길어 스크롤이 필요하므로 SingleChildScrollView를 사용합니다.
        body: SingleChildScrollView(
          child: MapPage(), // 누락된 클래스 이름을 MapPage로 지정
        ),
      ),
    );
  }
}

class MapPage extends StatelessWidget { // 클래스 이름을 MapPage로 지정했습니다.
  const MapPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 412,
          height: 917,
          clipBehavior: Clip.antiAlias,
          decoration: const BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              // LOWERVAILSBURG Text (폰트 제거)
              Positioned(
                left: 363.52,
                top: 282.70,
                child: SizedBox(
                  width: 131.48,
                  height: 14.53,
                  child: Text(
                    'LOWERVAILSBURG',
                    style: TextStyle(
                      color: const Color(0xFF606161),
                      fontSize: 8.07,
                      // 폰트 제거
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              // STREET Text (폰트 제거)
              Positioned(
                left: 164.07,
                top: 425.42,
                child: SizedBox(
                  width: 52.59,
                  height: 14.53,
                  child: Text(
                    'STREET',
                    style: TextStyle(
                      color: const Color(0xFF606161),
                      fontSize: 8.07,
                      // 폰트 제거
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              // UNION Text (폰트 제거)
              Positioned(
                left: 139.90,
                top: 115.46,
                child: SizedBox(
                  width: 47.66,
                  height: 14.53,
                  child: Text(
                    'UNION',
                    style: TextStyle(
                      color: const Color(0xFF606161),
                      fontSize: 8.07,
                      // 폰트 제거
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                ),
              ),
              // Rotated Text: street name (1)
              Positioned(
                left: 260.85,
                top: 242.52,
                child: SizedBox(
                  width: 44.76,
                  height: 10.06,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.33),
                    child: const Text(
                      'street name',
                      style: TextStyle(
                        color: Color(0xFF818181),
                        fontSize: 5,
                        // 폰트 제거
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              // Rotated Text: street name (2)
              Positioned(
                left: 301.30,
                top: 367.38,
                child: SizedBox(
                  width: 44.50,
                  height: 11.02,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.08),
                    child: const Text(
                      'street name',
                      style: TextStyle(
                        color: Color(0xFF818181),
                        fontSize: 5,
                        // 폰트 제거
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              // Rotated Text: street name (3)
              Positioned(
                left: 98.66,
                top: 354.02,
                child: SizedBox(
                  width: 51.16,
                  height: 8.33,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.31),
                    child: const Text(
                      'street name',
                      style: TextStyle(
                        color: Color(0xFF818181),
                        fontSize: 5,
                        // 폰트 제거
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              // Rotated Text: street name (4)
              Positioned(
                left: 203.76,
                top: 470.88,
                child: SizedBox(
                  width: 44.50,
                  height: 11.04,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.07),
                    child: const Text(
                      'street name',
                      style: TextStyle(
                        color: Color(0xFF818181),
                        fontSize: 5,
                        // 폰트 제거
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              // Rotated Text: street name (5)
              Positioned(
                left: 83.39,
                top: 130.30,
                child: SizedBox(
                  width: 52.69,
                  height: 5.15,
                  child: Transform(
                    transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(0.65),
                    child: const Text(
                      'street name',
                      style: TextStyle(
                        color: Color(0xFF818181),
                        fontSize: 5,
                        // 폰트 제거
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ),
              // 길찾기 Button Background
              Positioned(
                left: 343,
                top: 46,
                child: Container(
                  width: 53,
                  height: 41,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF2567E8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
              ),
              // 길찾기 Text
              Positioned(
                left: 349,
                top: 65,
                child: SizedBox(
                  width: 41,
                  height: 14,
                  child: Text(
                    '길찾기',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 10,
                      // 폰트 제거
                      fontWeight: FontWeight.w400,
                      height: 2,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),
              // Bottom Sheet Background
              Positioned(
                left: 0,
                top: 599,
                child: Container(
                  width: 412,
                  height: 308,
                  decoration: const ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(34),
                        topRight: Radius.circular(34),
                      ),
                    ),
                  ),
                ),
              ),
              // 바로가기 Text
              Positioned(
                left: 20,
                top: 638,
                child: Text(
                  '바로가기',
                  textAlign: TextAlign.center,
                  style: const TextStyle(
                    color: Colors.black,
                    fontSize: 25,
                    // 폰트 제거
                    fontWeight: FontWeight.w500,
                    height: 0.80,
                    letterSpacing: -0.24,
                  ),
                ),
              ),
              // Home Button Background
              Positioned(
                left: 20,
                top: 682,
                child: Container(
                  width: 70,
                  height: 70,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF2567E8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              // Home Text (집)
              Positioned(
                left: 45,
                top: 720,
                child: SizedBox(
                  width: 20,
                  height: 18,
                  child: Text(
                    '집',
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      // 폰트 제거
                      fontWeight: FontWeight.w500,
                      height: 1.33,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),
              // Home Icon Placeholder
              Positioned(
                left: 43,
                top: 688,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
              // Work Button Background
              Positioned(
                left: 121,
                top: 682,
                child: Container(
                  width: 70,
                  height: 70,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF2567E8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              // Work Text (직장)
              Positioned(
                left: 137,
                top: 720,
                child: SizedBox(
                  width: 37,
                  height: 18,
                  child: Text(
                    '직장',
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 15,
                      // 폰트 제거
                      fontWeight: FontWeight.w500,
                      height: 1.33,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),
              // Work Icon Placeholder
              Positioned(
                left: 144,
                top: 688,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
              // Add Button Background
              Positioned(
                left: 222,
                top: 682,
                child: Container(
                  width: 70,
                  height: 70,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(
                        width: 3,
                        color: Color(0xFF2567E8),
                      ),
                      borderRadius: BorderRadius.circular(15),
                    ),
                  ),
                ),
              ),
              // Add Text (+)
              Positioned(
                left: 239,
                top: 707,
                child: SizedBox(
                  width: 37,
                  height: 24,
                  child: Text(
                    '+',
                    textAlign: TextAlign.center,
                    style: const TextStyle(
                      color: Color(0xFF2567E8),
                      fontSize: 35,
                      // 폰트 제거
                      fontWeight: FontWeight.w900,
                      height: 0.57,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),

              // Bottom Navigation Bar Background (Blue)
              Positioned(
                left: 0,
                top: 827,
                child: Container(
                  width: 412,
                  height: 90,
                  decoration: const BoxDecoration(color: Color(0xFF2567E8)),
                ),
              ),
              // Bottom Nav Icons (Backgrounds & Placeholders)
              Positioned(
                left: 133,
                top: 832,
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: const ShapeDecoration(
                    color: Colors.white, // Center Icon (White)
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 834,
                child: Container(
                  width: 40,
                  height: 40,
                  decoration: const ShapeDecoration(
                    color: Color(0xFF2567E8), // Left Icon (Blue)
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 141,
                top: 840,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
              Positioned(
                left: 248,
                top: 842,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
              Positioned(
                left: 355,
                top: 842,
                child: Container(
                  width: 24,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
              Positioned(
                left: 34,
                top: 842,
                child: Container(width: 24, height: 24, child: const Stack()),
              ),

              // Search/Address Bar
              Positioned(
                left: 17,
                top: 46,
                child: Container(
                  width: 314,
                  height: 41,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: const BorderSide(
                        width: 3,
                        color: Color(0xFF2567E8),
                      ),
                      borderRadius: BorderRadius.circular(14),
                    ),
                  ),
                ),
              ),

              // Top Status Bar (Original)
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 412,
                  height: 32,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    // spacing property removed (invalid in Row/Column)
                    children: [
                      Row(
                        mainAxisSize: MainAxisSize.min,
                        mainAxisAlignment: MainAxisAlignment.start,
                        crossAxisAlignment: CrossAxisAlignment.start,
                        // spacing property removed (invalid in Row/Column)
                        children: [
                          Container(
                            width: 18,
                            height: 18,
                            clipBehavior: Clip.antiAlias,
                            decoration: const BoxDecoration(),
                            child: const Stack(),
                          ),
                          Container(width: 18, height: 18, child: const Stack()),
                          Container(
                            width: 18.75,
                            height: 18.75,
                            clipBehavior: Clip.antiAlias,
                            decoration: const BoxDecoration(),
                            child: const Stack(),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ),

              // Floating Icon (Bottom Right, near bottom bar)
              Positioned(
                left: 358,
                top: 887,
                child: Container(
                  width: 30,
                  height: 30,
                  clipBehavior: Clip.antiAlias,
                  decoration: const BoxDecoration(),
                  child: const Stack(),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}